project:
  type: website
  output-dir: docs
  
  render:
  - "*.qmd"

website:
  search: false
  navbar:
    background: "#06402B"
    left:
      - href: index.qmd
        text: "Sarah F. Hatch | Home"
    right: 
      - href: projects.qmd
        text: Ongoing Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



