project:
  type: website
  output-dir: docs
  
  render:
  - "*.qmd"

website:
  search: false
  navbar:
    background: "#A41034"
    left:
      - href: index.qmd
        text: "Sarah F. Hatch | Home"
    right: 
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



