---
title: "Ongoing Projects"
toc: false
---

I am a primary investigator on several projects examining what caregivers believe about social and emotional learning (SEL) and other politicized topics, and how those beliefs shape subsequent educational preferences. My work is funded by the Interdisciplinary Mind Grant from the Mind, Brain, Behavior Initiative at Harvard. 
I am also an active contributor in Stephanie Jones' [EASEL](https://easel.gse.harvard.edu/) lab and Dana McCoy's [SEED](https://seed.gse.harvard.edu/) lab. 


# Independently-Led Research

- **A Closer Look at Political Conservative's Views of SEL:** I conducted relational interviews in the Salt Lake and Utah Valleys to examine politically conservative parents' views of SEL (manuscript under review).
- **Features of SEL that Drive Opposition:** I used conjoint survey methods to explore differences in Republican and Democrat parents' (N=705) SEL-related preferences (contact for preliminary findings; analysis ongoing). 
- **Political and Psychological Predictors of Parents' School Censorship:** I used an experimental paradigm to examine predictors of parents' book censorship behaviors, using a mix of political and social psychology measures. *In partnership with Hannah Castner.* (manuscript under review).
- **Parenting Self-Efficacy, Psychological Safeguarding, and Censorship:** Drawing on Developmental Niche Theory and Item Response Theory, I developed and tested the validity evidence of two new measures of parenting beliefs which may predict parents' censorship behaviors (contact for preliminary findings; analysis ongoing). 


# Collaborative Research

- **Describing and Predicting Implementation Fidelity** I used Growth Curve Models to examine patterns of SEL implementation in after-school settings in Nebraska (manuscript in preparation, advised by Stephanie Jones).
- **Impacts of After-school SEL in Nebraska:** I provided logistical support and supported data management and collection for a large, state-wide RCT of SEL Kernels (manuscript in preparation, led by Stephanie Jones).
- **Impacts of Mobile Data Credits on Caregivers' Use of a Digital Parenting Intervention:** We find that small mobile data credits support extended use of an efficacious parenting intervention in high altitude Andean Peru (manuscript in preparation, advised by Lena Jaggi).


---